### ISSUE TITLE
Cfooter while there are two links with same key,the result can only see one piece of record.

### ISSUE THREAD

**Issue by yangecho** [PhoenixGrey/OODLIB#10]
![screenshot from 2015-11-20 15 22 02](https://cloud.githubusercontent.com/assets/15864358/11330312/7b974798-91e4-11e5-86b4-8f0882289f96.png)

while there are two links with same key,the result can only see one piece of record.

**Comment by PhoenixGrey** [comment]
@yangecho fixed in da31247
