### ISSUE TITLE
Caside when a part of the key does not exist,the result have no date，expect the fourth image .

### ISSUE THREAD

**Issue by yangecho** [PhoenixGrey/OODLIB#13]
![screenshot from 2015-12-01 09 44 20](https://cloud.githubusercontent.com/assets/15864358/11490450/cbffb3ca-9813-11e5-85c2-384ea8df316d.png)
![screenshot from 2015-12-01 09 44 20](https://cloud.githubusercontent.com/assets/15864358/11490454/d2bc0ed4-9813-11e5-9f76-aa0691bbd349.png)
![screenshot from 2015-12-01 10 14 00](https://cloud.githubusercontent.com/assets/15864358/11490534/64626338-9814-11e5-86eb-6a14e0593519.png)
![screenshot from 2015-12-01 10 19 32](https://cloud.githubusercontent.com/assets/15864358/11490650/922cae6c-9815-11e5-82fd-e82fddb754d3.png)

Caside when a part of the key does not exist,the result have no date,expect the fourth image.

**Comment by yangecho** [comment]
http://codepen.io/echoyang/pen/BoXvEJ
http://codepen.io/echoyang/pen/WQVLWy
http://codepen.io/echoyang/pen/KdObYG

**Comment by PhoenixGrey** [comment]
fix this in commit 9ca6b6e
