### ISSUE TITLE
Caside click the "nihao",the module is not highlighted

### ISSUE THREAD

**Issue by yangecho** [PhoenixGrey/OODLIB#15]
![screenshot from 2015-12-01 14 57 38](https://cloud.githubusercontent.com/assets/15864358/11494319/5479de56-983c-11e5-87c5-5c7099e804c6.png)

Caside click the "nihao",the module is not highlighted
http://codepen.io/echoyang/pen/ZbgPJK

**Comment by PhoenixGrey** [comment]
The key of the menu item has to be the same as its URL value. It is not a nice design, but it is not a bug. we will make it as a new feature to simplify the input info data.
