### ISSUE TITLE
[Caside] when click the first button, items bellow the first button also marked highlight ,expect not.

### ISSUE THREAD

**Issue by yangecho** [PhoenixGrey/OODLIB#16]
![screenshot from 2015-12-01 15 11 34](https://cloud.githubusercontent.com/assets/15864358/11494585/c65f0f4e-983e-11e5-9b6b-997786177163.png)
Caside click the "download", the modules under"download"below are also highlighted.
http://codepen.io/echoyang/pen/EVqMGR

**Comment by PhoenixGrey** [comment]
The same as the #15
