### ISSUE TITLE
Ctable info doesn't work, without title displaying

### ISSUE THREAD

**Issue by yangecho** [PhoenixGrey/OODLIB#2]
[Example](http://codepen.io/echoyang/pen/xwMOBq)
![screenshot from 2015-11-17 18 29 12](https://cloud.githubusercontent.com/assets/15864358/11208969/3511cbde-8d59-11e5-9257-09eefe5f551d.png)

info doesn't work, without title displaying

**Comment by PhoenixAndMachine** [comment]
@yangecho It has been repaired in commit da7f017
