### ISSUE TITLE
Ctable  when click the page's titles except nickname, the page flashing

### ISSUE THREAD

**Issue by yangecho** [PhoenixGrey/OODLIB#3]
![screenshot from 2015-11-17 18 47 41](https://cloud.githubusercontent.com/assets/15864358/11209413/d3a569b6-8d5b-11e5-97ae-968a73b925ce.png)

when click the page's titles except nickname, the page flashing

**Comment by PhoenixGrey** [comment]
@yangecho Please give an example.

**Comment by yangecho** [comment]
[Example](http://codepen.io/echoyang/pen/MaLpEb)

**Comment by PhoenixGrey** [comment]
@yangecho It has been built in commit 7dc28c8  

The table layout has been fixed.
