### ISSUE TITLE
Ctable without data ,the table display "总共0条记录"

### ISSUE THREAD

**Issue by yangecho** [PhoenixGrey/OODLIB#5]
[Example](http://codepen.io/echoyang/pen/xwMqKd)
![screenshot from 2015-11-17 18 13 34](https://cloud.githubusercontent.com/assets/15864358/11208632/5116c6a6-8d57-11e5-895c-b390d4eaf838.png)
"总共0条记录" should not show like this  picture.

**Comment by PhoenixGrey** [comment]
@yangecho fixed in  c88ad45
