### ISSUE TITLE
Ctable there is no a punctuation mark (:) indicating in data detail

### ISSUE THREAD

**Issue by yangecho** [PhoenixGrey/OODLIB#7]
![screenshot from 2015-11-17 11 30 53](https://cloud.githubusercontent.com/assets/15864358/11208479/5739e212-8d56-11e5-8a28-c25781b15066.png)
"详情
用户名称  Viola-PC
cpu 型号  Intel(R) Celeron(R) CPU G530 @ 2.40GHz
硬盘号  SV300S37A12
计算机序列  03000200-0400-0500-0006-000700080009
操作系统  Windows 7
"
There is no a punctuation mark (:) indicating. Expectation example(用户名称 : Viola-PC).

**Comment by PhoenixGrey** [comment]
@yangecho fixed in  584c4f8
