### ISSUE TITLE
Ctable have not  limited  the string's length  special characters

### ISSUE THREAD

**Issue by yangecho** [PhoenixGrey/OODLIB#8]
![screenshot from 2015-11-17 10 59 45](https://cloud.githubusercontent.com/assets/15864358/11208401/ef66f346-8d55-11e5-9cc0-18f9d2f9bd0a.png)
Ctable have not  limited  the string's length  special characters

**Comment by PhoenixGrey** [comment]
It will not have limitation of data length, however, the line break may be used in table as a feature

**Comment by PhoenixGrey** [comment]
@yangecho in commit 7dc28c8 , the long string will be ellipsis as `...`, however, the there are still inconsistency problems of `td-icon`.
